### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Indras91** [Inzaniak/sd-webui-ranbooru#18]
The error message is like this:
Error calling: /home/studio-lab-user/content/stable-diffusion-webui/extensions/ranbooru/scripts/ranbooru.py/ui
Traceback (most recent call last):
  File "/home/studio-lab-user/content/stable-diffusion-webui/modules/scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "/home/studio-lab-user/content/stable-diffusion-webui/extensions/ranbooru/scripts/ranbooru.py", line 268, in ui
    mature_rating = gr.Radio(RATINGS['gelbooru'].keys(), label="Mature Rating", value="All")
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/gradio/components.py", line 1140, in __init__
    self.test_input = self.choices[0] if len(self.choices) else None
TypeError: 'dict_keys' object is not subscriptable

Error calling: /home/studio-lab-user/content/stable-diffusion-webui/extensions/ranbooru/scripts/ranbooru.py/ui
Traceback (most recent call last):
  File "/home/studio-lab-user/content/stable-diffusion-webui/modules/scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "/home/studio-lab-user/content/stable-diffusion-webui/extensions/ranbooru/scripts/ranbooru.py", line 268, in ui
    mature_rating = gr.Radio(RATINGS['gelbooru'].keys(), label="Mature Rating", value="All")
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/gradio/components.py", line 1140, in __init__
    self.test_input = self.choices[0] if len(self.choices) else None
TypeError: 'dict_keys' object is not subscriptable

**Comment by SmashinFries** [comment]
What were your ranbooru settings? I'm having trouble replicating your error.

**Comment by Indras91** [comment]
> What were your ranbooru settings? I'm having trouble replicating your error.

The error appear suddenly after i installed the extension, not change anything

**Comment by Inzaniak** [comment]
Can you share the version of your Automatic1111 UI and the list of your installed extensions?

**Comment by Inzaniak** [comment]
Closed for inactivity
